errors = {
    "default": [400, "bad request"],
    "NotActivatedCard": [403, ""],
    "NoServicePermission": [403, ""],
    "InternalError": [500, ""],
    "TokenAuthenticationError": [401, ""],
    "ExpiredToken": [401, ""],
    "InvalidFormatError": [401, ""],
    "LoginError": [401, "一致するアカウントが存在しません。"],
    "LockedCard": [403, ""],
    "RequestDifferentAccounts": [400, ""],
    "ExceededBalanceLimit": [400, ""],
    "InsufficientBalance": [400, ""],
    "DisagreeTermsOfUse": [403, ""],
    "InvalidDate": [400, ""],
    "CanceledTransaction": [200, ""],
    "CanceledApplicationTransaction": [200, ""],
    "Success": [200, ""],
    "FirstLogin": [200, "入力されたメールアドレスに初期パスワード変更のメールを送信しました。\nメール内にあるリンクから初期パスワードを変更してください。"],
    "InitialPasswordMismatch": [400, ""],
    "NoApplicationInfomation": [400, ""],
    "NotExistCard": [400, ""],
    "NotExistCardConfig": [400, ""],
    "NotExistCampaign": [400, ""],
    "NotExistManagementTag": [400, ""],
    "NotExistCompany": [400, ""],
    "NotExistForcedGrant": [400, ""],
    "NotExistTransaction": [400, ""],
    "NotExistCancellationTransaction": [400, ""],
    "NotExistShop": [400, ""],
    "NotExistTerminal": [400, ""],
    "InvalidAccount": [403, ""],
    "UnauthorizedOperationError": [403, ""],
    "InvalidData": [400, ""],
    # Define Error Code & Message for API List Card
    "PaginatedError": [400, "Paginated error"],
    "InvalidDataListCardOffset": [400, "pager_position: invalid data."],
    "InvalidDataListCardLimit": [400, "pager_quantity: invalid data."],
    "InvalidDataListCardType": [400, "card_type: invalid data type."],
    "InvalidDataListCardStatus": [400, "card_status: invalid data type."],
    "InvalidDataListCardTestCard": [400, "testcard_flag: invalid data type."],
    # TODOKU email service
    "TodokuAuthError": [401, ""],
    "TodokuServerError": [500, ""],
}
