NONE = 0
DAY = 1
WEEK = 2
MONTH = 3
YEAR = 4

UNIT_CHOICES = (
    (NONE, 'なし'),
    (DAY, '日'),
    (WEEK, '週'),
    (MONTH, '月'),
    (YEAR, '年'),
)

VALUE_CHARGE_UNIT_DEFAULT = 1000

# Permissions
ISSUE_TOKEN = "ISSUE_TOKEN"
REFRESH_TOKEN = "REFRESH_TOKEN"
SET_INIT_PASSWORD = "SET_INIT_PASSWORD"
REVOKE_TOKEN = "REVOKE_TOKEN"
GET_CARD_LIST = "GET_CARD_LIST"
EXPORT_CARD_CSV = "EXPORT_CARD_CSV"
GET_CARD_DETAIL = "GET_CARD_DETAIL"
GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY"
EXPORT_TRANSACTION_CSV = "EXPORT_TRANSACTION_CSV"
GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL"
CREATE_TRANSACTION = "CREATE_TRANSACTION"
CANCEL_TRANSACTION = "CANCEL_TRANSACTION"
REQUEST_CANCEL_TRANSACTION = "REQUEST_CANCEL_TRANSACTION"
WITHDRAWAL_TRANSACTION_CANCEL_REQUEST = "WITHDRAWAL_TRANSACTION_CANCEL_REQUEST"
APPROVE_CANCEL_TRANSACTION_REQUEST = "APPROVE_CANCEL_TRANSACTION_REQUEST"
GET_CARD_SUMMARY = "GET_CARD_SUMMARY"
GET_BALANCE_SUMMARY = "GET_BALANCE_SUMMARY"
GET_EVENT_SUMMARY = "GET_EVENT_SUMMARY"
GET_ISSUE_TOTAL_SUMMARY = "GET_ISSUE_TOTAL_SUMMARY"
GET_ISSUE_TRANSITION_SUMMARY = "GET_ISSUE_TRANSITION_SUMMARY"

# Groups
ARARA = "arara"
AGENCY = "agency"
SHOP = "shop"
PROVIDER = "provider"

# Roles
OWNER = "owner"
MANAGER = "manager"
STAFF = "staff"

# Grants
ALLOW = 1
MUST_REQUEST = 2
DENIED = 3

STATE_CHOICE = (
    (ALLOW, '利用可能'),
    (MUST_REQUEST, '利用可能だが、一部操作で申請が必要'),
    (DENIED, '利用不可')
)
